version: "3.1"

pipeline:
  - name: HFTransformersNLP
    model_name: "bert-base-uncased"
    model_weights: "rasa/LaBSE"
  - name: LanguageModelTokenizer
  - name: LanguageModelFeaturizer
  - name: DIETClassifier
    epochs: 100

policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
