version: "3.1"
language: en
recipe: default.v1

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: DIETClassifier
    epochs: 50  # Reduced for Railway resource limits

policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 3  # Simplified for stability
    epochs: 50
