version: "3.1"
language: en
recipe: default.v1

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: DIETClassifier
    epochs: 20  # Reduced training time
    hidden_layers_sizes:
      text: [64, 32]  # Smaller layers
    constrain_similarities: true  # Fixes warnings

policies:
  - name: MemoizationPolicy
