import os

# Get the directory of this file
BASE_DIR = os.path.abspath(os.path.dirname(__file__))

class Config:
    # Use a relative path for the PDF file.
    # (Make sure you create a new folder called "data" and put your error-messages.pdf file there.)
    PDF_PATH = os.path.join(BASE_DIR, "data", "error-messages.pdf")
    
    # Use DATABASE_URL if provided (Railway will give you one if you add a PostgreSQL plugin).
    # Otherwise, fall back to an SQLite database (note: SQLite is ephemeral on Railway).
    SQLALCHEMY_DATABASE_URI = os.environ.get("DATABASE_URL") or \
        "sqlite:///" + os.path.join(BASE_DIR, "oracle_errors.db")
    
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SECRET_KEY = os.environ.get("SECRET_KEY") or "a-very-secret-key"

