version: "3.1"

# Add this line ⬇️
language: en

pipeline:
  - name: HFTransformersNLP
    model_name: "bert-base-uncased"
  - name: LanguageModelTokenizer
  - name: LanguageModelFeaturizer
  - name: DIETClassifier
    epochs: 100

policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
