version: "3.8"
services:
  rasa:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_URL=postgresql://user:pass@db:5432/errors
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=errors
